name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Install Upstream BCC Tools
      run: |
        sudo apt adv --keyserver keyserver.ubuntu.com --recv-keys 4052245BD4284CDD
        echo "deb https://repo.iovisor.org/apt/$(lsb_release -cs) $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/iovisor.list
        sudo apt update
        sudo apt install bcc-tools libbcc-examples linux-headers-$(uname -r)

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Generate BPF Sources
      run: go generate
      
    - name: Build
      run: go build -v .
